ALTER TABLE `t_order` ADD COLUMN `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号';
ALTER TABLE `t_order` ADD COLUMN `order_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '订单编号';
ALTER TABLE `t_order` ADD COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_order` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
